### ISSUE TITLE
notcurses_render moves cursor when writing to same position

### ISSUE THREAD

**Issue by FrankRuben** [dankamongmen/notcurses#2031]
Hi - and thanks for your inspiring work,

I'm getting some strange behavior, where writing to the same position using `ncplane_putchar_yx` will in fact write to the next x-position after `notcurses_render`. This can probably be explained better by a sample program.

The program below will first write the `2` (hence override the `1`) - as expected - but it will then display `23` (so writing to the next x-position) and then `24` (again overriding the last position).

Two additional minor annoyances:
* The cursor is displayed, where my understanding was, that it will be hidden by default. Trying to hide it via explicit call to `notcurses_cursor_disable` does not help.
* Once the program ends, `;1R` is written to the console.

``` C
#include <unistd.h>
#include <notcurses/notcurses.h>

struct nc_state {
  struct notcurses *nc;
  struct ncplane *stdp;
  int stdpy, stdpx;
};

int main(void) {
  const struct notcurses_options nc_options = (struct notcurses_options) {0};
  struct nc_state nc_state = (struct nc_state) {
    .nc = notcurses_core_init(&nc_options, NULL),
  };
  nc_state.stdp = notcurses_stddim_yx(nc_state.nc, &(nc_state.stdpy), &(nc_state.stdpx));

  ncplane_putchar_yx(nc_state.stdp, 10, 10, '1');

  ncplane_putchar_yx(nc_state.stdp, 10, 10, '2');
  notcurses_render(nc_state.nc);
  sleep(2); // 2

  ncplane_putchar_yx(nc_state.stdp, 10, 10, '3');
  notcurses_render(nc_state.nc);
  sleep(2); // 23

  ncplane_putchar_yx(nc_state.stdp, -1, -1, '4');
  notcurses_render(nc_state.nc);
  sleep(2); // 24

  notcurses_stop(nc_state.nc);
}
```

System information:

* `export | egrep 'LANG|LC_CTYPE|TERM'`
```
declare -x LANG="C.UTF-8"
declare -x TERM="xterm-256color"
```

* notcurses version (available from `notcurses-demo i`) - just pulled from current master:
```
$ ./notcurses-demo
+q544eGi=1,a=q;notcurses 2.3.13 on xterm-256color
30 rows 120 cols (56.25KiB) 48B crend 256 colors
gcc-9.3.0, 16B LE cells
terminfo from ncurses 6.2.20200212 zlib 1.2.11
built without multimedia support
```

* terminal name + version - running WSL2 on Windows '10.0.19042.1110':
```
$ uname -r
5.4.72-microsoft-standard-WSL2
```

**Comment by dankamongmen** [comment]
i'll take a look into it tonight! so this is WSL? interesting -- i'll try to reproduce it on my linux machine first, and if that doesn't work, i'll get a windows box up and check it out in WSL.

**Comment by dankamongmen** [comment]
@FrankRuben , i compiled this up on my Debian machine, and it worked exactly as expected, according to your description. i'm going to assume for now that this is some undesired interaction with WSL, and go test it there.

the bad news is that i am no expert in the windows environment, and it might take a bit longer than one would hope to get this resolved. the good news is that it will definitely get resolved. thanks for bringing it to my attention!

**Comment by FrankRuben** [comment]
Thanks for the update - and no need to hurry: this came up when doing some hobby-hacking, so I have no deadline to beat :).

**Comment by FrankRuben** [comment]
Not sure whether it helps or whether this is already known, but I also did test the same procedure with direct mode. Results:

The direct mode program below will first write the 2 (hence override the 1), it will then display 3 (so override the 2) and it will then write the 4 to the first column of the current row.

The cursor can now be disabled with an explicit call to `ncdirect_cursor_disable`, whereas a call to `ncdirect_cursor_enable` is not required at the end of the program.

Again the ;1R is written to the console, once the program ends.

Overall the direct mode on WSL is close enough for what I currently need.

```C
#include <unistd.h>
#include <notcurses/direct.h>

struct nc_state {
  struct ncdirect *nc;
  int termy, termx;
  uint64_t channels;
};

static inline void nc_direct_yx(struct nc_state *nc_state, int y, int x, const char* utf8) {
  ncdirect_cursor_move_yx(nc_state->nc, y, x);
  ncdirect_putstr(nc_state->nc, nc_state->channels, utf8);
}

int main(void) {
  const uint64_t nc_flags = 0u;
  FILE *fp = stdout;
  struct nc_state nc_state = (struct nc_state) {
    .nc = ncdirect_core_init(NULL, fp, nc_flags),
    .channels = 0,
  };
  nc_state.termy = ncdirect_dim_y(nc_state.nc);
  nc_state.termx = ncdirect_dim_x(nc_state.nc);
  ncchannels_set_fg_rgb(&nc_state.channels, 0xffffff);
  ncchannels_set_bg_rgb(&nc_state.channels, 0x0);

  ncdirect_cursor_disable(nc_state.nc);
  ncdirect_clear(nc_state.nc);

  nc_direct_yx(&nc_state, 10, 10, "1"); fflush(fp);

  nc_direct_yx(&nc_state, 10, 10, "2"); fflush(fp);
  sleep(2);

  nc_direct_yx(&nc_state, 10, 10, "3"); fflush(fp);
  sleep(2);

  nc_direct_yx(&nc_state, -1, -1, "4"); fflush(fp);
  sleep(2);

  ncdirect_stop(nc_state.nc);
  fputs("\n\n", fp);
}
```

**Comment by dankamongmen** [comment]
awesome writeup. i've been putting this off, but it's one of two remaining blockers for 2.3.14 (https://github.com/dankamongmen/notcurses/discussions/1905). appreciate your patience and further research!

**Comment by dankamongmen** [comment]
alright, i'm now able to reproduce this on my windows laptop

**Comment by dankamongmen** [comment]
alright. ten thousand apologies for the lengthy delay in getting back to you.

so, looking at your code, i believe the observed behavior is correct.

```c
  int stdpy, stdpx;                                                                                                          
};                                                                                                                           
                                                                                                                             
int main(void) {                                                                                                             
  const struct notcurses_options nc_options = (struct notcurses_options) {0};                                                
  struct nc_state nc_state = (struct nc_state) {                                                                             
    .nc = notcurses_core_init(&nc_options, NULL),                                                                            
  };                                                                                                                         
  nc_state.stdp = notcurses_stddim_yx(nc_state.nc, &(nc_state.stdpy), &(nc_state.stdpx));
```

...all good....

```
  ncplane_putchar_yx(nc_state.stdp, 10, 10, '1');                                                                            
                                                                                                                             
  ncplane_putchar_yx(nc_state.stdp, 10, 10, '2');                                                                            
  notcurses_render(nc_state.nc);                                                                                             
  sleep(2); // 2                                                                                                             
```

so after this, we expect to see only '2', and that is what we see.

```c                         
  ncplane_putchar_yx(nc_state.stdp, 10, 10, '3');                                                                            
  notcurses_render(nc_state.nc);
  sleep(2); // 23                                                                                                            
```

we should now see only 3, and we do
                                                                         
```
  ncplane_putchar_yx(nc_state.stdp, -1, -1, '4');                                                                            
  notcurses_render(nc_state.nc);                                                                                             
  sleep(2); // 24                                                                                                            
```                                                                                                                          

so we should now see `34`, which we do. this is because you've said stay in the same place that you were for both axes. but where you are is the space immediately following the 3, so the 4 goes there. 

from `notcurses_output(3notcurses)`:
>        If  a  positional  parameter  is  -1,  no  movement  will  be  made  along that axis.  Passing -1, -1 to e.g.  ncplane_putc_yx() is equivalent to calling the base form.  These functions are implemented by moving the cursor, and then  performing  the  output.  The two steps are atomic on success (it is not possible for another caller to move the cursor between when it is positioned, and when output begins), and thus these  functions  ought  generally  be preferred to an explicit ncplane_cursor_move_yx().

and below that:

>        Upon successful return, the cursor will follow the last cell output.

**Comment by dankamongmen** [comment]
oh but you're seeing `23` and `24`, right.

**Comment by dankamongmen** [comment]
alright, let me get my windows machine back up and get this resolved. i'm still on UNIX seeing, as expected, `2`, `3`, and finally `34`.

**Comment by dankamongmen** [comment]
should know what's up shortly

**Comment by dankamongmen** [comment]
hrmm, attempting to reproduce in WSL2 using Windows Terminal 1.9.1942.0 also gets the expected results: `2`, `3`, `34`

**Comment by dankamongmen** [comment]
`;1R` this is the trailing end of a Cursor Location Report; the fact that it's showing up suggests that we're misparsing it.

it might be helpful for you to run with `.loglevel = NCLOGLEVEL_INFO` or higher in your `notcurses_options`; that ought at least make the input issue plain.

you're running WSL, but through what terminal? Windows Terminal? mintty?

The cursor ought indeed be getting turned off, as you expect.

This isn't making much sense to me at all. Let me know what terminal emulator you're using. Also, what's the guest within the WSL? I can't reproduce this using Windows Terminal + WSL + Debian Unstablke -- your code runs as expected.

If you're not using Windows Terminal, can you try it out, and see if the behavior is different? If you are, is it the most recent version?

**Comment by dankamongmen** [comment]
The output of `notcurses-info -v` might also be instructive.

**Comment by dankamongmen** [comment]
I've also now tried it out in WSLtty, and get the same (expected, correct) results...hrmm =\. i think the `notcurses-info -v` output will provide the best insights from here.

**Comment by dankamongmen** [comment]
@FrankRuben , can you provide some more details about the environment in which you're running, especially the terminal and version? i'd like to get this knocked out, but can't reproduce it on either Windows Terminal or mintty =[.

**Comment by FrankRuben** [comment]
Hi,
thanks for taking care and sorry - I was away for a few days..., and I have just a few minutes for now: without going through the communication, just a quick update:

1. I did a `git pull` and did run `cmake` on my notcurses installation. (The version I used before was cloned just before I ran my initial tests.)
2. I did then run my first test case (using `notcurses.h`) again: now I'm getting: 2, 3, 34, which is the same that you got above.
3. I'm currently not using Windows Terminal, but I'm starting the WSL2 bash in cmd.exe, Windows version is '10.0.19042.1110'.
4. I'm not getting any specific version info from `notcurses-info -v` and its output looks OK.
5. I'll check the test case using `direct.h` tomorrow and update the info here.

**Comment by dankamongmen** [comment]
yay, i'm so glad you didn't wander off!

> I did then run my first test case (using notcurses.h) again: now I'm getting: 2, 3, 34, which is the same that you got above.

ok, so it sounds like you're no longer seeing the problem?

> I'm not getting any specific version info from notcurses-info -v and its output looks OK.

check out the top line; it ought start with `notcurses 2.3.17` or somesuch.

i'm gonna leave this open in case i misunderstood you, but i'm hoping your comment above indicates things have been resolved! fingers crossed

**Comment by FrankRuben** [comment]
So, finally some more details - overall we're getting close:

1. Yes, I'm no longer seeing the problem with the unexpected positioning: 2, 3, 34 is the expected output.

2. Also running the new version does no longer write the trailing ";1R"; but the cursor is still on while the program runs (and also still on once the program ends). 
So disabling the cursor does still not seem not work, even if I add an explicit call to `notcurses_cursor_disable`. When adding `notcurses_cursor_disable` and setting `loglevel = NCLOGLEVEL_DEBUG`, I'm getting:

```
notcurses_cursor_disable:1658:Cursor is not enabled
```

3. Complete version info for the updated test program is:

```
notcurses 2.3.17 on xterm-256color
terminfo from ncurses 6.2.20200212 zlib 1.2.11
```

Note: I posted some version info from `notcurses-demo` in my initial note:

```
notcurses 2.3.13 on xterm-256color
terminfo from ncurses 6.2.20200212 zlib 1.2.11
```

And I'm still finding a `libnotcurses.so.2.3.13` with the date of the initial runs, so that initial version should have been 2.3.13.

4. The test version for direct mode still writes the same and expected output: 2, 3, 4. 
But this test case still writes the trailing ";1R"; here again the cursor is off while the program runs and on once the program ends. 
So the confusing bit here seems to be the trailing ";1R".

Hope that helps - and I'm now (sadly) back at home, so communication is now back at internet speed :).

Thanks again, Frank

**Comment by dankamongmen** [comment]
no, thank you man!

i've created two new bugs about the material here, and plan to call the primary issue resolved. does that sound reasonable to you?

**Comment by FrankRuben** [comment]
> 
> 
> no, thank you man!
> 
> i've created two new bugs about the material here, and plan to call the primary issue resolved. does that sound reasonable to you?

yes, absolutely - my summary has been that we have one open item for not-direct mode (cursor not disabled) and one open item for direct mode (trailing ";1R"), which fits your issues.

**Comment by dankamongmen** [comment]
yep. i started work on them last night, but was very tired. hopefully i can knock them out tonight or tomorrow. i've scheduled both for 2.4.
